# Master configuration file for the acrn driver.
# All settings described here are optional - if omitted, sensible
# defaults are used.

# Path to a directory with firmware files. By default it's pointing
# to the directory that sysutils/acrn-firmware installs files into.
#firmware_dir = "/usr/share/acrn/bios"
